name: Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 22.x ]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
        env:
          NODE_ENV: test

      - name: Build app
        run: npm run build

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'

      - name: Commit and push to app branch
        run: |
          # Create and checkout app branch
          git checkout -b app || git checkout app
          
          # Remove gitignore and verify git status
          rm .gitignore
          git status
          pwd
          
          # Move to app directory and verify location
          cd app/
          pwd
          ls -la
          
          # Add all files
          git add .
          
          # Verify files were added
          cd ..
          git status
          
          # Commit and push
          git commit -m "Update built app files [skip ci]" || echo "No changes to commit"
          git push -f origin app
